# Generated by Django 3.0.5 on 2022-05-02 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toppings',
            options={'verbose_name_plural': 'Toppings'},
        ),
    ]
